vich_uploader:
    db_driver: orm

    mappings:
        circuit_image:
            uri_prefix: /images/circuits
            upload_destination: '%kernel.project_dir%/public/images/circuits'
            namer : Vich\UploaderBundle\Naming\UniqidNamer
        etape_image:
            uri_prefix: /images/etapes
            upload_destination: '%kernel.project_dir%/public/images/etapes'
            namer : Vich\UploaderBundle\Naming\UniqidNamer
